module.exports = {
    COMMUNITY_CHAT:"COMMUNITY_CHAT",
    USER_CONNECTED:"COMMUNITY_CHAT",
    MESSEGE_RECEIVED:"MESSEGE_RECEIVED",
    MESSEGE_SENT:"MESSEGE_SENT",
    USER_DISCONNECTED:"USER_DISCONNECTED",
    TYPING:"TYPING",
    VERIFY_USER:"VERIFY_USER",
    LOGOUT:"LOGOUT"
}